Fix workdir missing omitempty directive
This was breaking existing YAML files because they didn't contain
`workdir`:

```
Error: Error reading myTask/myTask.yml

Node: workdir is required
```